# Generated by Django 5.1.6 on 2025-03-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200)),
                ('c_email', models.CharField(max_length=50)),
                ('c_address', models.CharField(max_length=200)),
                ('c_phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.IntegerField()),
                ('o_name', models.CharField(max_length=100)),
                ('o_quantity', models.IntegerField(max_length=20)),
                ('o_time', models.TimeField()),
            ],
        ),
    ]
